# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" "it87" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/418a47c0-5a3f-422b-8b71-d35ed4dea7be";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1B15-159F";
      fsType = "vfat";
    };

  fileSystems."/mnt/bitcoin" =
    { device = "/dev/disk/by-uuid/b7bb7370-e615-4a6f-9de7-8eb767af0369";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f861d972-5c8e-4d9a-89de-a58cb1d6f850"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
}
